apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build: 
  local: 
    push: false
  artifacts: 
    - image: ayzin/client
      context: client
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: 'src/**/*.js'
            dest: .
    - image: ayzin/comments
      context: comments
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: '*.js'
            dest: .
    - image: ayzin/event-bus
      context: event-bus
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: '*.js'
            dest: .
    - image: ayzin/moderation
      context: moderation
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: '*.js'
            dest: .
    - image: ayzin/posts
      context: posts
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: '*.js'
            dest: .
    - image: ayzin/query
      context: query
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: '*.js'
            dest: .